In [1]:
import torch

In [16]:
## + - * /

x = torch.randn(2, 3)
y = torch.randn(2, 3)

print(x + 1)
print(x * 2)
print(x / 2)
print(x // 2)
print(x % 2)
print(x ** 2)


tensor([[ 2.1785,  0.7787,  0.1899],
        [ 1.4559,  3.0754, -1.1336]])
tensor([[ 2.3570, -0.4426, -1.6201],
        [ 0.9118,  4.1508, -4.2672]])
tensor([[ 0.5892, -0.1107, -0.4050],
        [ 0.2279,  1.0377, -1.0668]])
tensor([[ 0., -1., -1.],
        [ 0.,  1., -2.]])
tensor([[1.1785, 1.7787, 1.1899],
        [0.4559, 0.0754, 1.8664]])
tensor([[1.3888, 0.0490, 0.6562],
        [0.2078, 4.3072, 4.5523]])


In [17]:
print(x + y)
print(x - y)

tensor([[-0.0792,  0.6597, -1.8564],
        [-1.4120,  1.6204, -1.1274]])
tensor([[ 2.4362, -1.1023,  0.2363],
        [ 2.3238,  2.5304, -3.1398]])


In [25]:
print(x * y) ## 多维数组点积

tensor([[-1.4821, -0.1950,  0.8476],
        [-0.8515, -0.9443, -2.1469]])


In [24]:
t1 = torch.rand(5)
t2 = torch.rand(5)
print(t1.dot(t2)) ## 向量点积
print(t1 * t2) ## 向量乘法

tensor(1.4817)
tensor([0.4403, 0.7613, 0.2226, 0.0534, 0.0041])


In [28]:
print(x @ y.T) ## 矩阵乘法
print(x.matmul(y.T)) ## 矩阵乘法 等价

tensor([[-0.8295, -2.9157],
        [ 3.4877, -3.9427]])
tensor([[-0.8295, -2.9157],
        [ 3.4877, -3.9427]])


In [30]:
torch.sum(x), x.sum()

(tensor(0.5448), tensor(0.5448))

In [31]:
x.mean(), x.std(), x.max(), x.min()

(tensor(0.0908), tensor(1.4908), tensor(2.0754), tensor(-2.1336))

In [42]:
x = torch.randn(4, 8)
print(x)
x.argmax(dim=0), x.argmax(dim=1)

tensor([[-0.7515,  1.1541, -0.1996,  0.9855,  1.0936,  1.4017,  1.0355, -1.7407],
        [ 0.4392,  0.2108, -0.3594,  0.0281, -1.2477, -2.4945, -0.4699, -0.9193],
        [ 1.9439, -1.3838, -1.9861, -0.3584, -0.5671, -0.1157,  1.0791,  0.7713],
        [ 1.2859,  0.2801, -0.7650, -0.0260,  2.6776,  0.5064, -0.4770,  0.3957]])


(tensor([2, 0, 0, 0, 3, 0, 2, 2]), tensor([5, 0, 0, 4]))

In [43]:
torch.softmax(x, dim=0), torch.softmax(x, dim=1)

(tensor([[0.0374, 0.5303, 0.3864, 0.4979, 0.1623, 0.6068, 0.4021, 0.0415],
         [0.1229, 0.2065, 0.3293, 0.1911, 0.0156, 0.0123, 0.0892, 0.0945],
         [0.5533, 0.0419, 0.0647, 0.1299, 0.0308, 0.1330, 0.4200, 0.5122],
         [0.2865, 0.2213, 0.2195, 0.1811, 0.7912, 0.2479, 0.0886, 0.3518]]),
 tensor([[0.0275, 0.1846, 0.0477, 0.1559, 0.1737, 0.2364, 0.1639, 0.0102],
         [0.2627, 0.2090, 0.1182, 0.1741, 0.0486, 0.0140, 0.1058, 0.0675],
         [0.4773, 0.0171, 0.0094, 0.0477, 0.0388, 0.0609, 0.2010, 0.1478],
         [0.1465, 0.0536, 0.0188, 0.0395, 0.5892, 0.0672, 0.0251, 0.0601]]))

In [44]:
torch.sum(torch.softmax(x, dim=0), dim=0)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [57]:
x = torch.rand(4, 6)
print(x)

tensor([[0.9670, 0.3357, 0.8644, 0.6208, 0.9424, 0.4411],
        [0.8051, 0.7560, 0.8025, 0.3908, 0.6207, 0.5438],
        [0.2756, 0.4879, 0.8958, 0.6889, 0.7119, 0.9294],
        [0.6386, 0.5716, 0.4340, 0.3871, 0.9074, 0.3091]])


In [56]:
print(x.view(12, -1))

tensor([[0.3209, 0.1944],
        [0.2006, 0.4661],
        [0.6581, 0.1889],
        [0.9730, 0.5405],
        [0.3410, 0.3508],
        [0.0200, 0.4326],
        [0.0102, 0.0977],
        [0.9022, 0.4762],
        [0.7938, 0.1112],
        [0.2108, 0.7414],
        [0.8996, 0.1698],
        [0.3816, 0.8483]])


In [58]:
# 创建一个连续存储的张量
a = torch.arange(12).reshape(3, 4)
print("原始张量 a:\n", a)
print("是否连续存储:", a.is_contiguous())

# 使用 view 改变形状
b = a.view(4, 3)
print("\n视图 b:\n", b)

# 改变视图 b 的数据
b[0, 0] = 99
print("\n改变 b 后，原始张量 a:\n", a)
# 输出: 99 也出现在 a 中

原始张量 a:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
是否连续存储: True

视图 b:
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

改变 b 后，原始张量 a:
 tensor([[99,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [59]:
a.flatten()

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
print(a > 3)

tensor([[ True, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


In [62]:
print(a[a > 3])

tensor([99,  4,  5,  6,  7,  8,  9, 10, 11])


In [63]:
a.is_contiguous()

True

In [86]:
x = torch.tensor([1, 2, 3, 4])  # shape: [4]
print(x.shape)
# ====== unsqueeze ======
x_unsq = x.unsqueeze(0)         # 在dim=0加一维
print(x_unsq.shape)             # torch.Size([1, 4])

x_unsq2 = x.unsqueeze(1)        # 在dim=1加一维
print(x_unsq2.shape)            # torch.Size([4, 1])

# ====== squeeze ======
y = torch.randn(1, 4, 1, 3)     # shape: [1, 4, 1, 3]
y_sq = y.squeeze()              # 自动去掉所有 size=1 的维度
print(y_sq.shape)               # torch.Size([4, 3])

y_sq_dim1 = y.squeeze(2)        # 只去掉 dim=2 (如果大小是1)
print(y_sq_dim1.shape)          # torch.Size([1, 4, 3])


torch.Size([4])
torch.Size([1, 4])
torch.Size([4, 1])
torch.Size([4, 3])
torch.Size([1, 4, 3])


In [92]:
import torch.nn.functional as F

input = torch.randn(3, 4)
output = F.softmax(input, dim=0)
print(output)
output = F.relu(input)
print(output)
output = F.sigmoid(input)
print(output)

tensor([[0.7700, 0.0747, 0.3005, 0.4190],
        [0.1595, 0.5399, 0.2865, 0.4149],
        [0.0706, 0.3854, 0.4130, 0.1661]])
tensor([[2.1230, 0.0000, 0.2434, 0.0000],
        [0.5484, 0.0000, 0.1957, 0.0000],
        [0.0000, 0.0000, 0.5614, 0.0000]])
tensor([[0.8931, 0.1064, 0.5605, 0.3844],
        [0.6338, 0.4624, 0.5488, 0.3821],
        [0.4336, 0.3805, 0.6368, 0.1985]])
