## 线性回归

In [13]:
import torch
import torch.nn as nn


class LinearNN(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.linear = nn.Linear(in_features, out_features)

    def forward(self, x):
        return self.linear(x)

In [24]:
X = torch.rand(100, 2)
weight = torch.tensor([2.0, 3.0])
bias = 4
y = X @ weight + bias + torch.randn(100)*0.01
X[:10], y[:10]

(tensor([[0.3205, 0.5930],
         [0.1359, 0.4212],
         [0.0290, 0.5357],
         [0.9512, 0.2693],
         [0.7310, 0.5179],
         [0.5992, 0.7047],
         [0.7197, 0.8714],
         [0.9044, 0.3224],
         [0.4034, 0.9349],
         [0.0260, 0.7980]]),
 tensor([6.4147, 5.5313, 5.6705, 6.7208, 7.0098, 7.3037, 8.0442, 6.7397, 7.6122,
         6.4485]))

In [31]:
model = LinearNN(2, 1)

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.05)

for epoch in range(1000):
    model.train()
    y_pred = model(X).squeeze()
    loss = criterion(y_pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if epoch % 5 == 0:
        print(f"Epoch [{epoch:03d}/100]  Loss: {loss.item():.4f}")

model.linear.weight, model.linear.bias


Epoch [000/100]  Loss: 39.7502
Epoch [005/100]  Loss: 33.5919
Epoch [010/100]  Loss: 28.0029
Epoch [015/100]  Loss: 23.0109
Epoch [020/100]  Loss: 18.6273
Epoch [025/100]  Loss: 14.8457
Epoch [030/100]  Loss: 11.6429
Epoch [035/100]  Loss: 8.9817
Epoch [040/100]  Loss: 6.8136
Epoch [045/100]  Loss: 5.0833
Epoch [050/100]  Loss: 3.7315
Epoch [055/100]  Loss: 2.6987
Epoch [060/100]  Loss: 1.9280
Epoch [065/100]  Loss: 1.3668
Epoch [070/100]  Loss: 0.9686
Epoch [075/100]  Loss: 0.6936
Epoch [080/100]  Loss: 0.5091
Epoch [085/100]  Loss: 0.3889
Epoch [090/100]  Loss: 0.3128
Epoch [095/100]  Loss: 0.2661
Epoch [100/100]  Loss: 0.2380
Epoch [105/100]  Loss: 0.2213
Epoch [110/100]  Loss: 0.2111
Epoch [115/100]  Loss: 0.2045
Epoch [120/100]  Loss: 0.1997
Epoch [125/100]  Loss: 0.1956
Epoch [130/100]  Loss: 0.1919
Epoch [135/100]  Loss: 0.1882
Epoch [140/100]  Loss: 0.1846
Epoch [145/100]  Loss: 0.1809
Epoch [150/100]  Loss: 0.1772
Epoch [155/100]  Loss: 0.1735
Epoch [160/100]  Loss: 0.1699
Epo

(Parameter containing:
 tensor([[2.0543, 3.0594]], requires_grad=True),
 Parameter containing:
 tensor([3.9390], requires_grad=True))

In [ ]:
with torch.no_grad():
    y_test = model(X).squeeze()

from matplotlib import pyplot as plt
plt.figure()
# 可视化预测与实际值
plt.scatter(X[:, 0], y, color='blue', label='True values')
plt.scatter(X[:, 0], y_test, color='red', label='Predictions')
plt.legend()
plt.show()